version: '3.8'

services:
  web:
    build: ./api
    command: gunicorn --bind 0.0.0.0:8000 api.wsgi:application
    volumes:
      - ./api:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: ./api
    command: celery -A api worker --loglevel=info
    volumes:
      - ./api:/app
    environment:
      - DJANGO_DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_beat:
    build: ./api
    command: celery -A api beat --loglevel=info
    volumes:
      - ./api:/app
    environment:
      - DJANGO_DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  static_volume:
  media_volume: