# Generated by Django 5.2rc1 on 2025-03-31 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='post_interval_hours',
        ),
        migrations.AddField(
            model_name='client',
            name='post_interval_days',
            field=models.IntegerField(default=1, help_text='Days between each blog post generation'),
        ),
        migrations.AddField(
            model_name='client',
            name='post_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Time of day to post (24-hour format)'),
        ),
    ]
