# Generated by Django 5.2rc1 on 2025-04-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_client_post_interval_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToneOfVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of this tone of voice')),
                ('cached_examples', models.TextField(blank=True, help_text='Cached version of example posts for GPT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='gpt_prompt',
            field=models.TextField(help_text="Description of the client's needs and industry-specific requirements"),
        ),
        migrations.AddField(
            model_name='client',
            name='tone_of_voice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='blogs.toneofvoice'),
        ),
        migrations.CreateModel(
            name='ToneOfVoiceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tone_of_voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_posts', to='blogs.toneofvoice')),
            ],
        ),
    ]
