# Generated by Django 5.2rc1 on 2025-04-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_toneofvoice_alter_client_gpt_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toneofvoice',
            name='cached_examples',
        ),
    ]
