# Generated by Django 5.2rc1 on 2025-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_toneofvoice_cached_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='AI detection score (0-100, lower is more human-like)', null=True),
        ),
    ]
