# Generated by Django 5.2rc1 on 2025-04-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_specialevent_blogsubject_blogpost_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tone_of_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examples', to='blogs.toneofvoice'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blogs.client'),
        ),
        migrations.DeleteModel(
            name='ToneOfVoiceExample',
        ),
    ]
