# Generated by Django 5.2rc1 on 2025-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blogpost_tone_of_voice_alter_blogpost_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tone_of_voice',
        ),
        migrations.AddField(
            model_name='toneofvoice',
            name='examples',
            field=models.ManyToManyField(blank=True, related_name='used_as_example_for', to='blogs.blogpost'),
        ),
    ]
