# Generated by Django 5.2rc1 on 2025-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blogpost_tone_of_voice_toneofvoice_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='Generated thumbnail description for image generation', null=True),
        ),
    ]
