# Generated by Django 5.2rc1 on 2025-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='URL or description for the thumbnail image', null=True),
        ),
    ]
