# Generated by Django 5.2rc1 on 2025-04-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_client_completed_onboarding_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='completed_onboarding',
        ),
    ]
