# Generated by Django 5.2rc1 on 2025-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_remove_onboarding_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gpt_prompt',
        ),
        migrations.AddField(
            model_name='client',
            name='business_description',
            field=models.TextField(blank=True, help_text='A detailed description of your business, products, and services', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='content_preferences',
            field=models.TextField(blank=True, help_text='The type of blog posts you want to generate', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, help_text='The industry your business operates in', max_length=200, null=True),
        ),
    ]
